# Generated by Django 4.2 on 2023-06-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Rate Price"
                    ),
                ),
                (
                    "vip_question",
                    models.CharField(max_length=3, verbose_name="VIP Question"),
                ),
                (
                    "vip_discount_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="VIP Discount Rate"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Cost"
                    ),
                ),
                (
                    "discount_enabled",
                    models.BooleanField(default=False, verbose_name="Discount Enabled"),
                ),
            ],
        ),
    ]
