# Generated by Django 4.2 on 2023-06-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate_price", models.FloatField()),
                ("vip_question", models.CharField(max_length=3)),
                ("vip_discount_rate", models.FloatField()),
                ("hour", models.FloatField()),
                ("minute", models.IntegerField()),
                ("cost", models.FloatField()),
                ("discount_enabled", models.BooleanField(default=False)),
            ],
        ),
    ]
